### PR TITLE
Add support for using short term STS IAM credentials

### PR DESCRIPTION
**Pull request by jarrod-lowe**
Adds support for using IAM credentials which are issued by the STS service, and therefore require a SessionToken.

I have used this with the http-basic-auth method and by specifying the config in the config file, but I was unsure of how to generate a JWT token to test that path with.

### CODE REVIEW

**Comment by markushinz** [comment]
Nice, LGTM. Could you bump the version in `version.txt` to 1.11.0? The file is used to compute the new release version.
BTW the pipeline is failing because secrets are not passed to forks.

**Comment by jarrod-lowe** [comment]
Sure, version number bumped

**Comment by markushinz** [comment]
Could you also make sure that all commits are signed?

**Comment by jarrod-lowe** [comment]
signed now

**Pull request merged**
